name: Real Estate News Bot
on:
  schedule:
    - cron: '30 23 * * *' # 한국시간 오전 8:30
    - cron: '30 8 * * *'  # 한국시간 오후 5:30
  workflow_dispatch: # 직접 버튼 눌러서 실행해보고 싶을 때 사용
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 필요 도구 설치
        run: pip install python-telegram-bot requests
      - name: 비서 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
        run: python bot.py
